<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstractsyntaxrestassured" nsURI="http://www.example.org/abstractsyntaxrestassured"
    nsPrefix="abstractsyntaxrestassured">
  <eClassifiers xsi:type="ecore:EClass" name="TestRoundtrip" instanceTypeName="TestRoundtrip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenwhen" lowerBound="1"
        eType="#//RequestSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" upperBound="-1"
        eType="#//ResponseSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestSpecification" instanceTypeName="RequestSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" lowerBound="1" eType="#//Request"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenparam" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenauth" lowerBound="1"
        eType="#//AuthenticationSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseSpecification" instanceTypeName="ResponseSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticationSpecification" instanceClassName="AuthenticationSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Param" instanceClassName="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request" instanceClassName="Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//Method"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Method" instanceClassName="Method">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicAuthentication" instanceClassName="BasicAuthentication"
      eSuperTypes="#//AuthenticationSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusCode" instanceClassName="StatusCode"
      eSuperTypes="#//ResponseSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Body" instanceClassName="Body" eSuperTypes="#//ResponseSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status" instanceClassName="Status">
    <eLiterals name="200"/>
    <eLiterals name="400" value="1"/>
  </eClassifiers>
</ecore:EPackage>
