<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="puml" nsURI="http://www.eclipse.plantuml/Puml" nsPrefix="puml">
  <eClassifiers xsi:type="ecore:EClass" name="UmlDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlDiagrams" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassUml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlElements" upperBound="-1"
        eType="#//ClassElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceUml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlElements" upperBound="-1"
        eType="#//SequenceElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentUml">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlElements" upperBound="-1"
        eType="#//ComponentElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritance" eType="#//Inheritance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//ClassContent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="divider" upperBound="-1"
        eType="#//DividerClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="advancedBody" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDef" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceDef" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superTypes" unique="false"
        upperBound="-1" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedInterfaces"
        unique="false" upperBound="-1" eType="#//Classifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlClassTitle" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumConstants" upperBound="-1"
        eType="#//EnumConstant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConstant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//ClassContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//ClassContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//Visibility"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classLeft" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationArrow" eType="#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoRight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRight" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoteClass" eSuperTypes="#//ClassElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//NotePosition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noteOf" eType="#//Classifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="note" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DividerClass" eSuperTypes="#//ClassContent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dividerText" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NotePosition">
    <eLiterals name="LEFT" literal="left"/>
    <eLiterals name="RIGHT" value="1" literal="right"/>
    <eLiterals name="TOP" value="2" literal="top"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssociationType">
    <eLiterals name="BIDIRECTIONAL" literal="BIDIRECTIONAL"/>
    <eLiterals name="DIRECTIONALLEFT" value="1" literal="DIRECTIONALLEFT"/>
    <eLiterals name="DIRECTIONALLEFTX" value="2" literal="DIRECTIONALLEFTX"/>
    <eLiterals name="DIRECTIONALLEFTO" value="3" literal="DIRECTIONALLEFTO"/>
    <eLiterals name="DIRECTIONALRIGHT" value="4" literal="DIRECTIONALRIGHT"/>
    <eLiterals name="DIRECTIONALRIGHTX" value="5" literal="DIRECTIONALRIGHTX"/>
    <eLiterals name="DIRECTIONALRIGHTO" value="6" literal="DIRECTIONALRIGHTO"/>
    <eLiterals name="INHERITANCELEFT" value="7" literal="INHERITANCELEFT"/>
    <eLiterals name="INHERITANCERIGHT" value="8" literal="INHERITANCERIGHT"/>
    <eLiterals name="AGGREGATIONLEFT" value="9" literal="AGGREGATIONLEFT"/>
    <eLiterals name="AGGREGATIONRIGHT" value="10" literal="AGGREGATIONRIGHT"/>
    <eLiterals name="COMPOSITIONLEFT" value="11" literal="COMPOSITIONLEFT"/>
    <eLiterals name="COMPOSITIONRIGHT" value="12" literal="COMPOSITIONRIGHT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="PROTECTED" literal="#"/>
    <eLiterals name="PRIVATE" value="1" literal="-"/>
    <eLiterals name="DEFAULT" value="2" literal="~"/>
    <eLiterals name="PUBLIC" value="3" literal="+"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Participant" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QualifiedName"/>
  <eClassifiers xsi:type="ecore:EClass" name="Space" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" unique="false" upperBound="-1"
        eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Divider" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="noteOf" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Newpage" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title" eSuperTypes="#//SequenceElement #//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Legend" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legendEntries" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegendEntries">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Autonumber" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlElementsContainer" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="umlElements" upperBound="-1"
        eType="#//SequenceElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skinparam" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skinElements" upperBound="-1"
        eType="#//SkinElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SkinElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlUse" eSuperTypes="#//SequenceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="userOne" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationArrow" eType="#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userTwo" eType="#//Participant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameExtension" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkOne" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationArrow" eType="#//AssociationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTwo" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EQUALDIVIDER" eSuperTypes="#//DividerClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="DASHEDDIVIDER" eSuperTypes="#//DividerClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="UNDERLINEDIVIDER" eSuperTypes="#//DividerClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="DOTEDDIVIDER" eSuperTypes="#//DividerClass"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activate" eSuperTypes="#//UmlElementsContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activate" eType="#//Participant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deactivate" eType="#//Participant"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//UmlElementsContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBlocks" upperBound="-1"
        eType="#//UmlElementsContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Else" eSuperTypes="#//UmlElementsContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//UmlElementsContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="test" unique="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//UmlElementsContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UseLeft" eSuperTypes="#//UmlUse"/>
  <eClassifiers xsi:type="ecore:EClass" name="UseRight" eSuperTypes="#//UmlUse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//NamedElement"/>
</ecore:EPackage>
